### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by andrew-hossack** [dkedar7/fast_dash#11]
* Fast Dash version: 0.1.6
* Python version: 3.7.8
* Operating System: MacOS

### Description

Trying to get fast-dash working with Heroku deployments. I would like to do something like this:

```
from fast_dash import FastDash
from fast_dash.Components import Text

# Step 1: Define your model inference
def text_to_text_function(input_text):
    return input_text

# Step 2: Specify the input and output components
app = FastDash(callback_fn=text_to_text_function, 
                inputs=Text, 
                outputs=Text, 
                title='App title')

# Declare server for Heroku deployment. Needed for Procfile.
server = app.server

if __name__ == '__main__':
    app.run()
```

Running the file gives me an error: `AttributeError: 'FastDash' object has no attribute 'server'`

Any advice?

**Comment by dkedar7** [comment]
You'll have to use `app.app.server` instead of `app.server`. Let me know if this works.

`app` is just the Fast Dash object, whereas `app.app` is the Dash object. And so, the Flask server that you can deploy with a server framework like gunicorn is `app.app.server`.

Deploying to Heroku is a great use case! Let me know what you end up building; I'd love to share it with the community.
